name: Deploy in kubernetes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: create kubeconfig
      run: |
        sudo -i
        sudo mkdir ${home}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${home}/.kube/config
        cat ${home}/.kube/config
    - name: use context
      run: kubectl config use-context minikube
    - name: create ns in k8s
      run: kubectl create namespace test
